#!/bin/sh

echo "                                                        ";
echo "\e[32m________________________________________________        ";
echo "________________________________________________        ";
echo "             _ _ _                         _            ";
echo "  /\/\   ___(_) (_)___  ___  __ _ _ __ ___| |__         ";
echo " /    \ / _ \ | | / __|/ _ \/ _` | '__/ __| '_ \        ";
echo "/ /\/\ \  __/ | | \__ \  __/ (_| | | | (__| | | |       ";
echo "\/    \/\___|_|_|_|___/\___|\__,_|_|  \___|_| |_|       ";
echo "                                                        ";
echo "________________________________________________        ";
echo "________________________________________________        \e[39m";
echo "                                                        ";
echo "Welcome to your Meilisearch server                      ";
echo "                                                        ";
echo "    Documentation: https://docs.meilisearch.com         ";
echo "    Sources: https://github.com/meilisearch/meilisearch ";
echo "    Support: https://discorg.gg/meilisearch             ";
echo "                                                        ";
echo "                                                        ";
echo "   ___________________________________________________  ";
echo "                                                        ";
echo "   To setup Meilisearch use command: meilisearch-setup  ";
echo "   ___________________________________________________  ";
echo "                                                        ";
